export enum THEME_NAME_ENUM {
  THEME_BLUE = 'THEME_BLUE',
  THEME_RED = 'THEME_RED',
  THEME_PINK = 'THEME_PINK',
}

export type THEME_NAMES_TYPE = {
  THEME_BLUE: string;
  THEME_RED: string;
  THEME_PINK: string;
};

export const THEME_NAMES: THEME_NAMES_TYPE = {
  THEME_BLUE: THEME_NAME_ENUM.THEME_BLUE,
  THEME_PINK: THEME_NAME_ENUM.THEME_PINK,
  THEME_RED: THEME_NAME_ENUM.THEME_RED,
};
